# 定时任务的时区
CronZone: 'Asia/Shanghai'

# 飞书机器人
FeiShuRobotUrl: ''

# Server酱
ChanKey: ''

# 定时
## 基金估值
FundWorthCron:
  - ''

## 股票估值
StockWorthCron:
  - ''

## 基金阈值监控
FundMonitorCron:
  - ''

## 股票阈值监控
StockMonitorCron:
  - ''

## 基金历史监控
FundHisMonitorCron:
  - ''

## 股票历史监控
StockHisMonitorCron:
  - ''

## 阈值监控任务广播
BroadMonitorCron:
  - ''

## 历史监控任务广播
HisBroadMonitorCron:
  - ''
