# 定时任务的时区
CronZone: 'Asia/Shanghai'

# 飞书机器人
FeiShuRobotUrl: ''

# Server酱
ChanKey: ''

# 定时
## 基金净值
FundWorthCron:
  - ''

## 股票净值
StockWorthCron:
  - ''

## 基金监控
FundMonitorCron:
  - ''

## 股票监控
StockMonitorCron:
  - ''

## 监控任务广播
BroadMonitorCron:
  - ''
